### ISSUE TITLE
Would you mind creating a release?

### ISSUE THREAD

**Issue by sundbp** [rksm/ace.improved#1]
Hi,

I'm thinking of using ace.improved from clojurescript and was going to create a cljsjs wrapper. For that it'd be great to have a release so that I could point my task to e.g. a fixed github release zip file or similar for download.

Thanks!

**Comment by rksm** [comment]
Will do, let me create some doc first...

**Comment by rksm** [comment]
0.2.1 is tagged and on npm now.

**Comment by sundbp** [comment]
Thanks!
